### ISSUE TITLE
Embedded Scripting & Containerisation

### ISSUE THREAD

**Issue by ajlennon** [m3y54m/Embedded-Engineering-Roadmap#5]
Also use of embedded scripting languages and containerisation is going to be another big need in the future

- MicroPython / Circuit Python

- Docker for Embedded (e.g. meta-docker for Yocto, Balena.io, Foundries.io, Mender.io)

**Comment by m3y54m** [comment]
Python is already on the roadmap. Anyone who knows Python and has some knowledge about microcontrollers can learn MicroPython / Circuit Python in a week. Additionally, these two languages are primarily used in hobby projects rather than in industry.

Although the use of Docker is increasing in all areas of software development, it is still not an essential skill for an embedded developer.

**Comment by ajlennon** [comment]
>Anyone who knows Python and has some knowledge about microcontrollers can learn MicroPython / Circuit Python in a week.

Nope. Programming firmware, adding native driver support, the limitations on an embedded system. All different and all key

> Additionally, these two languages are primarily used in hobby projects rather than in industry.

That was the case. It's changing. For example Swarm.space have been shipping their space gateway EVKs with CircuitPython for a long time now.

>Although the use of Docker is increasing in all areas of software development, it is still not an essential skill for an embedded developer.

I disagree, but as I say you have your views and I have mine.

**Comment by ajlennon** [comment]
I'll add that people are bound to disagree on this stuff. Irrespecfive of what you or I think should go in I think you've done a brilliant job here and I will definitely be showing this to students, academics and others to give them an idea of what the job entails!
